version: "3.4"

services:
  mockbackendapiserver:
    image: mockbackendapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  mongo:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
